esphome:
  name: test1

esp8266:
  board: d1_mini_lite

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: 

ota:
  password: 

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Hatest1 Fallback Hotspot"
    password: "MQUNzeNz8sWE"

captive_portal:

servo:
  - id: my_servo
    output: pwm_output
    restore: True
    transition_length: 1s

# the PWM output for the servo
output:
  - platform: esp8266_pwm
    id: pwm_output
    pin: D7
    frequency: 50 Hz

# expose it to HA?
number:
  - platform: template
    name: Servo Control
    min_value: -100
    max_value: 100
    step: 1
    optimistic: true
    set_action:
      then:
        - servo.write:
            id: my_servo
            level: !lambda 'return x / 100.0;'
